name: Go Check

on:
  push:
    branches: [ "main", "master" ] # Запускать при пуше в эти ветки
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Или твоя версия Go

    - name: Install dependencies
      run: go mod download

    - name: Run Tests
      # Эта команда запустит все тесты и твои Example функции
      run: go test -v ./...
